version: '3'

services:
    server:
        restart: unless-stopped
        build: .
        ports:
            - "80:80"
            - "443:443"
        environment:
            POSTGRES_CONNECTION_STRING: "Host=db;Database=win;Username=win;Password=win"
        depends_on:
            - "db"
        restart: always
    db:
        restart: unless-stopped
        image: postgres:11
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "win"
            POSTGRES_USER: "win"
            POSTGRES_PASSWORD: "win"
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
  db-data: